version: '3'

services:
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 'a1b2c3d4'
      MYSQL_DATABASE: 'contatos'
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  app:
    build: .
    container_name: flask
    environment:
      MYSQL_HOST: 'database'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'a1b2c3d4'
      MYSQL_DATABASE: 'contatos'
    command: ["bash", "-c", "sleep 30 && flask run --host=0.0.0.0 --port=80"]
    ports:
      - "80:80"
    depends_on:
      - database

volumes:
  db_data:
