version: '3'

services:
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'a1b2c3d4'
  #     MYSQL_DATABASE: 'contatos'
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - mynetwork

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 'a1b2c3d4'
      MYSQL_DATABASE: 'contatos'
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - mynetwork


  app:
    build: .
    container_name: flask
    environment:
      MYSQL_HOST: 'database'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'a1b2c3d4'
      MYSQL_DATABASE: 'contatos'
    #command: ["sh", "-c", "while ! telnet database 3306; do sleep 5; done && mysql --version"]
    #command: ["sh", "-c", "while ! mysql --version; do sleep 5; done && mysql --version"]
    ports:
      - "80:80"
    depends_on:
      - database
    links:
      - database
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
