version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: a1b2c3d4
      MYSQL_DATABASE: contatos
     # MYSQL_USER: root
      #MYSQL_PASSWORD: a1b2c3d4
    ports:
      - "3306:3306"
